# nonk8s
apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: murmurations/allocator
      platforms: ["linux/arm64","linux/amd64"]
      context: .
      docker:
        dockerfile: docker/Dockerfile-dev
deploy:
  helm:
    releases:
    - name: development
      chartPath: murmurationsAllocator
      setValues:
        image: murmurations/allocator
      valuesFiles:
      - murmurationsAllocator/values.yaml
      version: 0.1.0
      setValueTemplates:
        sourcepath: "{{.SOURCEPATH}}"
