apiVersion: v1
kind: ConfigMap
metadata:
  name: allocator-app-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: "5s"
  SERVER_TIMEOUT_WRITE: "10s"
  SERVER_TIMEOUT_IDLE: "15s"
  MONGO_DB_NAME: "mapdata"
