apiVersion: apps/v1
kind: Deployment
metadata:
  name: allocator-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: allocator-app
  template:
    metadata:
      labels:
        app: allocator-app
    spec:
      containers:
        - name: allocator-app
          image: {{ .Values.image }}
          envFrom:
            - configMapRef:
                name: allocator-app-config
            - secretRef:
                name: allocator-app-secret
      {{- if eq .Values.env "development" }}
          volumeMounts:
            - mountPath: /src/allocator
              name: source-path
      volumes:
          - name: source-path
            hostPath:
              path: {{ .Values.sourcepath }}
      {{- end }}
