apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allocator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if not (eq .Values.env "development") }}
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if eq .Values.env "production" }}
  tls:
    - hosts:
        - allocator.murmurations.network
      secretName: murmurations-allocator-tls
  {{- else if eq .Values.env "staging" }}
  tls:
    - hosts:
        - test-allocator.murmurations.network
      secretName: murmurations-allocator-tls
  {{- end }}
  rules:
    {{- if eq .Values.env "production" }}
    - host: allocator.murmurations.network
    {{- else if eq .Values.env "staging" }}
    - host: test-allocator.murmurations.network
    {{- else }}
    - host: allocator.murmurations.dev
    {{- end }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: allocator-app
                port:
                  number: {{ .Values.service.port }}