apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allocator-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - {{ .Values.url }}
      secretName: allocator-app-tls
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: allocator-app
                port:
                  number: {{ .Values.allocator.service.port }}