apiVersion: v1
kind: Service
metadata:
  name: allocator-app
spec:
  selector:
    app: allocator-app
  ports:
    - name: allocator-app
      protocol: TCP
      port: {{ .Values.allocator.service.port }}