name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker images
        run: make push

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.TEST_SERVER_IP }}
      KUBECONFIG_PATH: ${{ secrets.KUBECONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_ENV: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy Services
        run: ./scripts/deploy-services.sh
